; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; defines the environment: it could be arduino or esp32 for this case.
[env:esp32dev]
; This tells Platform IO which chip family to download tools for esp32
platform = espressif32
; The specific board variant
board = esp32dev
; Writing the code the arduino way
framework = arduino
monitor_speed = 115200
lib_deps =
    ESP32 Arduino

